### PR TITLE
Add Transformer-based NER classifier using Hugging Face models

### PR DESCRIPTION
**Pull request by lfcc1**
**What's in the PR**
* Added a TransformerNerClassifier class that allows to perform Named Entity Recognition using pre-trained models from Hugging Face's transformers.

**How to test**
* Run test file: pytest tests/test_transformer_recommender.py

### CODE REVIEW

**Comment by reckart** [comment]
@lfcc1 build fails

**Comment by lfcc1** [comment]
> @lfcc1 build fails

My bad. I commented some dependencies in the setup.py file for my specific use case. I just corrected it.

**Comment by reckart** [comment]
@lfcc1 Looks like there is still some problem with the requirements.

**Comment by lfcc1** [comment]
@reckart Missed a comma, could you try again?

**Pull request merged**
