### PR TITLE
#12 - Add jupyter notebook

### PR DESCRIPTION
**Pull request by nkolmar**
- Add a jupyter notbook containing the external recommender tutorial

### CODE REVIEW

**Review by jcklie — APPROVED** [review]
Very nice. I maybe would add a screenshot for the results at the beginning and at the end, the link to the documentation renders badly for me.

**Comment by nkolmar** [comment]
> Very nice. I maybe would add a screenshot for the results at the beginning and at the end, the link to the documentation renders badly for me.

Thanks for your feedback. I added a screenshot. What do you mean by the link to the documentation rendering poorly?

**Comment by jcklie** [comment]
image

Sorry to be annoying but I would use a NER screenshot, the POS is overwhelming I find. I would also accept some annotations to have different colors in there.

**Comment by nkolmar** [comment]
Ok. No problem, you are right, thanks for your advice. I added NER screenshots instead of POS screenshots and I think it looks better now. I also escaped the link to the documentation, is it now rendering correctly for you?

**Comment by jcklie** [comment]
Looks good!

**Pull request merged**
